// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SomeConvenientWidgetModuleScssNamespace {
  export interface ISomeConvenientWidgetModuleScss {
    fadeIn: string;
    widget: string;
    widgetButton: string;
    widgetText: string;
  }
}

declare const SomeConvenientWidgetModuleScssModule: SomeConvenientWidgetModuleScssNamespace.ISomeConvenientWidgetModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SomeConvenientWidgetModuleScssNamespace.ISomeConvenientWidgetModuleScss;
};

export = SomeConvenientWidgetModuleScssModule;
