// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppLoaderModuleScssNamespace {
  export interface IAppLoaderModuleScss {
    fadeIn: string;
    loaderSpinner: string;
    loaderText: string;
  }
}

declare const AppLoaderModuleScssModule: AppLoaderModuleScssNamespace.IAppLoaderModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppLoaderModuleScssNamespace.IAppLoaderModuleScss;
};

export = AppLoaderModuleScssModule;
